CMakeLists.txt
autodiff/forward/forward.hpp
test/catch.hpp
test/forward.test.cpp

This PR fixes the issue reported in #41 and potentially others in which as the expression tree is constructed at compile time, some expression nodes are taken accidentally as reference, and then going out of scope.

Fix segmentation fault and accidental reference to out of scope expression nodes

---

CMakeLists.txt
autodiff/forward/forward.hpp
environment.devenv.yml
test/forward.test.cpp

This PR fixes the issue reported in #47. It has been identified that aliasing is causing the derivatives to be wrong. A fix is proposed, in which `const auto aux = ...` are replaced by `const T aux = ...`, to force the right-hand side of the temporary to be constructed as a Dual type instead of an expression.

Fix higher order derivatives

---

README.md

Hi, Allan.
I was curious about autodiff and found a very minor problem. PR's reason is provided below:
This PR performs a very minor fix. In the autodiff's README from master branch, the expression tree figure is not properly loaded. This PR just update the link, pointing to the correct place.

Fix expression tree figure linking in README

---

CMakeLists.txt
autodiff/forward/forward.hpp
autodiff/reverse/reverse.hpp

This PR satisfies (partially) the requirement asked in issue #55 .
One can now, in addition to using method `val`, use `static_cast<double>` to convert a `var` object into `double`.

Add explicit double convert operator for var

---

autodiff/forward/forward.hpp
examples/forward/example-forward-higher-order-derivatives.cpp
test/forward.test.cpp

Add new wrt function overloading. As we discussed #57 users want to use simpler way of higher-order derivatives calculation. I remember that @allanleal thought about changing dual implementation, but I'm not sure that it is necessary and easy to implement. Also, we will get regressions using such an approach. 
```cpp
using dual4th = Dual<double, 4>;
dual4th x = 1.0;
dual4th y = derivative(sin, wrt(x), at(x));
cout << y[0] << endl; // value of the 0th order derivative of sin(x), which is its actual value
cout << y[1] << endl; // value of the 1st order derivative of sin(x)
cout << y[2] << endl; // value of the 2nd order derivative of sin(x)
cout << y[3] << endl; // value of the 3rd order derivative of sin(x)
cout << y[4] << endl; // value of the 4th order derivative of sin(x)
```
Here we …

[autodiff/forward] Simplify higher order derivatives

---

autodiff/forward/forward.hpp
test/forward.test.cpp

This is a fix for issue #62 in which template expression objects were being stored in other expression objects by reference. 
However, the use case in issue #62 still needs to be corrected. 
Consider the following usage of `dual`:
~~~c++
#include <iostream>
#include <autodiff/forward.hpp>
using namespace autodiff;
template <typename T>
auto pow2(T arg)
{
return arg * arg;
}
int main()
{
dual x = 2.0;
dual y = pow2(pow2(x));
std::cout << y << std::endl;
}
~~~
This application outputs `nan` or produces a segmentation fault. The reason is that argument `arg` in `pow2` is passed by value, so a temporary `dual` is created when calling `pow2(x)` in `main`. 
This temporary `dual` is then captured by reference when creating the template expression node 
`BinaryExpr<MulOp, const dual&, const …

Fix nan and/or segfault when using nested template functions

---

autodiff/reverse/eigen.hpp

This PR allows for mixing VectorXvar and VectorXd types in element-wise binary operations such as
```c++
VectorXvar x(3); x << 1.0, 2.0, 3.0;
VectorXd y(3); x << 2.0, 2.0, 2.0;
x+y;
x-y;
x*y;
x.cwiseQuotient(y);
```
This is a fix for issue #81

added ScalarBinaryOpTraits for var and double

---

autodiff/forward/forward.hpp
test/forward.test.cpp

This PR adds Erf to forwards mode with a test.
Note that Erf (and other special functions) in Eigen are UnaryOps which apply to array objects, e.g:
```c++ 
VectorXdual x; 
erf(x.array());
```
Some special math functions are in the Eigen header (cf [Eigen bugzilla](https://eigen.tuxfamily.org/bz/show_bug.cgi?id=1775)):
``
#include <unsupported/Eigen/SpecialFunctions>
``

Erf forwards

---

autodiff/reverse/reverse.hpp
test/forward.test.cpp

This PR tidies up from PR #83 and #84.

tweak for erf. sqrt_pi literal in reverse. Removed Eigen header from forward

---

autodiff/forward/forward.hpp
examples/forward/example-forward-single-variable-function-custom-scalar.cpp

In this PR we make enable to use autodiff dual with custom scalars. Also example is added. Also improved dual construction. Resolve issue #91.
- Re-implement constructor with parameter to make enable use implicit construction:
```cpp
using dual_cmpx = forward::Dual<complex<double>, complex<double>>;
// ...
dual_cmpx x = 2.0;
```
If we use scalar which can be implicit constructed from e.g. from `double` above code is not legal with 
implementation:
```cpp
Dual(const ValueType<T>& val)
: val(val), grad(0)
{
}
```
After substitution we have something like this:
```cpp
Dual(const std::complex<double>& val)
: val(val), grad(0)
{
}
```
And this conversation is prevented by standard [see this link](https://stackoverflow.com/a/17348767).
- Added Structure `isNumber` which can be specialized in …

Make autodiff forward friendly with custom numbers

---

.github/workflows/linux.yml
.github/workflows/osx.yml
.github/workflows/windows.yml
autodiff/forward/eigen.hpp
ci/actions/install.sh
ci/actions/test.sh
environment.devenv.yml
examples/forward/example-forward-gradient-derivatives-using-eigen-with-parameters.cpp
examples/forward/example-forward-gradient-derivatives-using-eigen-with-scalar.cpp
examples/forward/example-forward-hessian-derivatives-using-eigen-with-scalar.cpp

Hi @allanleal and `autodiff` contributors!
This PR removes `conda` manual installation. Now, using a GitHub Action, `conda` will be used from CI machines.
In summary, this PR is a CI improvement. It solves #96

Use built-in miniconda from GH action

---

autodiff/forward/eigen.hpp

This PR fixes issue #97 (thanks @danilomendesdias!) in which `Eigen::ScalarBinaryOpTraits` was not configured properly for general `Dual<T, G>` where `T` can also be another `Dual` number of one order below its parent.

Fix issue #97 about ScalarBinaryOpTraits not configured correctly

---

autodiff/forward/eigen.hpp

As reported in #103 , when removing `using namespace Eigen`, compile errors show up. This is a fix for this.

Fix usage of Eigen library without using namespace

---

CMakeLists.txt

This PR is to address the need to allow users to specify the path to Eigen3 as follows:
~~~
cd autodiff
mkdir build
cd build
cmake .. -DEIGEN3_INCLUDE_DIR=/path/to/downloaded/eigen-3.3.7
make 
~~~

Allow EIGEN3_INCLUDE_DIR to be provided during cmake configuration

---

autodiff/reverse/reverse.hpp
test/reverse.test.cpp

This PR fixes issue #17. It was detected that the problem was due to operators `+=, -=, *=, /=` in `Variable` type not properly dealing with temporaries.

Fix operator+=, -=, *=, /= for Variable

---

autodiff/common/meta.hpp
autodiff/forward/eigen.hpp
autodiff/forward/forward.hpp
autodiff/reverse/reverse.hpp

Hi,
this is not actually very important, but at least for the project I'm working on these warnings trigger, so I decided to resolve them. Maybe there is also some benefit for other people... 
There shouldn't be any change in functionality, just some variable renaming and additional default constructors/destructors...). I also did not resolve the warnings in the tests. The only warnings I still get are related to Eigen.

resolve some warnings (-Wextra, -Wshadow, -Wnon-virtual-dtor)

---

.bazelrc
.github/workflows/windows.yml
.gitignore
BUILD
WORKSPACE
autodiff/BUILD
ci/actions/install.sh
ci/actions/test.sh
examples/forward/BUILD
examples/reverse/BUILD
test/BUILD

This PR introduces [bazel.build](https://bazel.build/) for the usage within bazel projects
- Bazel WORKSPACE file
- Bazel BUILD files
- Integration of examples as cc_test
- Could enable a better CI testing
- People can use autodiff in their Bazel projects easily

Integrate bazel.build 

---

autodiff/forward/forward.hpp
autodiff/reverse/reverse.hpp
test/forward.test.cpp
test/reverse.test.cpp

Perhaps a minor issue, but there is currently a discrepancy between the reverse and forward modes for ```abs(x)``` at ```x=0```, where reverse mode returns derivative ```+1``` and forward results in a NaN after division by zero. Though the regular derivative is undefined at ```x=0``` it seems better to compute one of the sub-derivatives in ```[-1, 1]``` instead of dividing by zero.
I chose 0 here which seemed nice and symmetric and is what e.g. ```pytorch``` does.

Return zero sub-gradient for abs(x) at x=0

---

.github/workflows/linux.yml
.github/workflows/osx.yml
.github/workflows/windows.yml

GH Actions had an update in October that require us to update `setup-miniconda` in `autodiff` CI. The `setup-miniconda` needs to be bumped to `v2` for all builds.
I'm updating it because one day the CI build would break.

Update setup-miniconda GH action version

---

autodiff/common/meta.hpp
autodiff/forward/forward.hpp
autodiff/reverse/reverse.hpp

This PR does resolves some warnings triggered by `-Wunused-parameter` on clang. It would be great if this could be merged in, since this triggers the MacOS CI configuration in a project where I want to use `autodiff`.

resolving -Wunused-parameter warnings for clang

---

CMakeLists.txt
autodiff/reverse/reverse.hpp
test/reverse.test.cpp

This PR implements missing comparison operators for `reverse::Variable` and `reverse::ExprPtr`. This fixes issue #137 .

Implement missing comparison operators between Variable and ExprPtr

---

autodiff/forward/eigen.hpp
autodiff/forward/forward.hpp
test/forward.test.cpp

1. Allow cast vectors of HigherOrderDual to Eigen::VectorXd
2. Fix problem with expression eval for HigherOrderDual related to wrong recursive ValueType meta function.
3. Make Eigen related functions compatible with HigherOrderDual.

Fixes for higher order dual numbers

---

tests/forward/dual/dual.test.cpp
tests/forward/real/real.test.cpp

This PR fixes the failing tests from #167 by using std::abs for the absolute value of floating point values in the forward dual and real tests.
However, why the tests in #167 did not fail for @allenleal remains unknown.
Closes #167.

Fix #167: Use std::abs for floating point values in tests

---

.gitignore

I need to use autodiff for a C++ project. When I try to install it by CMake, I found that files under the .build directory haven't be ignored yet.

Modified build files path in .gitignore

---

autodiff/common/eigen.hpp

Implement support for `wrt(x(indices))` by defining `VectorTraits` for `Eigen::IndexedView`. This PR enables the following:
~~~c++
auto J = jacobian(f, wrt(x(indices)), at(x));
~~~
So that `J` is the Jacobian of `f` w.r.t. only `x` variables within `indices`.

Implement support for wrt(x(indices))

---

autodiff/forward/utils/gradient.hpp
docs/website/tutorials.md
examples/forward/example-forward-jacobian-derivatives-using-eigen-map.cpp
tests/forward/utils/gradient.test.cpp

Allows, `gradient()`, `jacobian()`, and `hessian()` to write to pre-allocated storage. Examples and tests use `Eigen::Map` to write to a POD double array, but any object which implements `resize(n, m)`, `rows()`, `cols()` and `operator(i, j)` can be used.

Adds support and examples for using Eigen::Map

---

.clang-format
autodiff/reverse/var/var.hpp
docs/website/tutorials.md
examples/reverse/example-reverse-conditional.cpp
tests/reverse/var/var.test.cpp

Initial implementation only, only supports simple boolean expressions
comparing Expr<T> and related classes, not yet conjunctions between
boolean expressions themselves
- Add nullary update fn to Expr<T> interface for back-propagating value
changes in nodes of an expression tree, implement for all existing
derived classes
- Replace virtual keyword with override in Expr<T>-derived classes
- Introduce BooleanExpr to capture arbitrary comparison between two
Expr<T>
- Introduce ConditionalExpr to capture switching between two expressions
depending on the value of a BooleanExpr
- Change boolean operators to return BooleanExpr's
- Alter semantics of Variable<T>::operator=(Numeric ) and
Variable<T>::operator[+-*/]=(Numeric x) to alter the underlying
independent variable if set without …

Implement reverse prop condition expr

---

autodiff/forward/utils/gradient.hpp

The following snippet does not compile against master since `std::vector` does not have a `rows` member (a la Eigen I guess). This patch fixes the issue.
```cpp
auto f = [](const auto& v){
using Vector = std::decay_t<decltype(v)>;
Vector ret(v.size());
auto s = std::accumulate(v.begin(), v.end(), typename Vector::value_type(0));
std::transform(v.begin(), v.end(), ret.begin(), [=](auto& vv){ return vv * s; });
return ret;
};
std::vector<dual> x = {1,2,3,4,5};
std::vector<dual> F;
Eigen::MatrixXd J = jacobian(f, wrt(x), at(x), F);
std::cout << "F = \n";
for (const auto& v : to)
std::cout << v << ", ";
std::cout << "\n";
std::cout << "J =\n" << J << "\n";
```
Current compilation error:
```terminal
autodiff/forward/utils/gradient.hpp:130:28: error: no member named 'rows' in …
```

Call VectorType.size rather than rows

---

autodiff/common/vectortraits.hpp

[Proposal]
This small change allows for sfinea-like specialization of the `VectorTraits` struct, e.g.
```cpp
struct Foo {};
struct Bar : Foo {};
struct Blarg : Foo {};
namespace autodiff::detail {
/// Specialize VectorTraits for Foo & derived.
template <typename T> struct VectorTraits<T, EnableIf<std::is_base_of_v<Foo, T>>> { ... };
}
```
Thus offering more flexibility in the specialization.
Other traits may benefit from this feature as well but so far I did not needed to change any other to add support to `autodiff` in my project.

Allow sfinae specialization on VectorTraits

---

autodiff/BUILD

Bazel requires all included header files to be listed, otherwise it reports errors such as 
```
this rule is missing dependency declarations for the following files included by 'YOUR_PROGRAM.cpp':                               
'external/com_github_autodiff_autodiff/autodiff/common/binomialcoefficient.hpp'                                              
'external/com_github_autodiff_autodiff/autodiff/common/numbertraits.hpp'                                                     
'external/com_github_autodiff_autodiff/autodiff/common/vectortraits.hpp'
```

Fix missing dependencies in Bazel

---

.gitignore
CMakeLists.txt
environment.devenv.yml
python/package/CMakeLists.txt
python/package/setup.py.in

This PR improves the installation of the Python package (named `autodiff`) produced during the compilation of `autodiff`. It now uses `pip`.

Fix pip install

---

autodiff/common/classtraits.hpp
autodiff/forward/utils/gradient.hpp
examples/forward/example-forward-gradient-derivatives.cpp

#224 introduced a change in access operator call that broke backward compatibility. The compilation fails when using types that implement the `operator [](int)` but does not implement the `operator ()(int)` (such as most std containers).
The example [`example-forward-gradient-derivatives.cpp`](https://github.com/artivis/autodiff/blob/798c6e6e9545347c0d8671ecc98c87a65309ad83/examples/forward/example-forward-gradient-derivatives.cpp), introduced in this PR, wouldn't compile while `std::vector` seems to be a first-class citizen of `autodiff`.
This PR implements a traits to check whether the vector type implement the `operator [](int)` and calls it. It falls back to `operator ()(int)` otherwise.
Without more context about #224 I don't know if this fix requires further attention.
Closes #233.

Fix backward compatibility break

---

cmake/autodiffInstallCMakeConfigFiles.cmake

autodiff is a header only library. Therefore no check of architecture is required. If one does not disable this, CMake will complain if autodiff was built in 64 bit but later on is used by a 32 bit application.

CMake: Avoid check of architecture.

---

autodiff/forward/dual/dual.hpp
autodiff/reverse/var/var.hpp
tests/reverse/var/var.test.cpp

This PR fixes the issue reported in #243 in which higher-order derivatives for `hypot` function was not correct.
With the changes included here, the following code works as expected:
~~~c++
#include <autodiff/reverse/var.hpp>
#include <iostream>
using namespace autodiff;
int main()
{
var x = 1.0;
var y = 1.0;
{
var u = hypot(x, y);
auto [ux, uy] = derivativesx(u, wrt(x, y));
auto [uxx, uxy] = derivativesx(ux, wrt(x, y));
auto [uyx, uyy] = derivativesx(uy, wrt(x, y));
std::cout << "u = " << u << std::endl;
std::cout << "ux = " << ux << "\nuy = " << uy << std::endl;
std::cout << "[uxx, uxy] = [" << uxx << ", " << uxy << "]\n"
<< "[uyx, uyy] = [" << uyx << ", " << uyy << "]" << std::endl;
}
{
var u = sqrt(x * x + y * y);
auto [ux, uy] = derivativesx(u, wrt(x, y));
auto [uxx, uxy] = …

Fix computation of reverse higher order derivatives involving `hypot(x, y)` and `hypot(x, y, z)`

---

docs/website/installation.md
environment.devenv.yml
tests/CMakeLists.txt
tests/common/meta.test.cpp
tests/forward/dual/dual.test.cpp
tests/forward/dual/eigen.test.cpp
tests/forward/utils/derivative.test.cpp
tests/main.cpp
tests/reverse/var/eigen.test.cpp
tests/reverse/var/var.test.cpp
tests/utils/catch.hpp

This PR migrates Catch2 from v2 to v3, following the [migration instructions](https://github.com/catchorg/Catch2/blob/devel/docs/migrate-v2-to-v3.md#top).
@allanleal Catch is also used in `test/BUILD`. I see in the [installation instructions](https://autodiff.github.io/installation/) that this is for the [Bazel](https://bazel.build/) build system. I never used it before and I can't see it in the CI builds; is there any documentation related to `autodiff` about this?
Fix #246

Migrate Catch2 from v2 to v3

---

CMakeLists.txt
autodiff/common/eigen.hpp
autodiff/common/meta.hpp
autodiff/forward/utils/gradient.hpp
autodiff/reverse/var/eigen.hpp
tests/forward/dual/eigen.test.cpp
tests/forward/real/eigen.test.cpp

This PR introduces support for the use of `Eigen::Map` when using `autodiff::gradient`, `autodiff::jacobian`, `autodiff::hessian`.
It also introduces some static asserts to ensure that entries in the `wrt` lists are non-const.
Fixes #194

Support the use of `Eigen::Map`

---

CMakeLists.txt
python/bindings/real.py.cxx
python/package/autodiff/__init__.py

This PR introduces the following new methods to the Python API of `autodiff::real` number types:
- `autodiff.seed(x: autodiff.real)`
- `autodiff.unseed(x: autodiff.real)`
- `autodiff.__format__` (to permit Python formatted strings such as `f"{x:.3f}"` where `x` is `real`
- `autodiff.__deepcopy__` (to permit the use of autodiff numbers in plotly plots

Improve and extend the Python API of `autodiff::real` types
